# Generated by Django 3.0.2 on 2020-01-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='data de modificação')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='data de modificação')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='AnswerNumeric',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='responses.AnswerBase')),
                ('body', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='resposta')),
            ],
            options={
                'verbose_name': 'Resposta de valor numérico',
                'verbose_name_plural': 'Respostas de valor numérico',
            },
            bases=('responses.answerbase',),
        ),
        migrations.CreateModel(
            name='AnswerRadio',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='responses.AnswerBase')),
                ('body', models.TextField(blank=True, null=True, verbose_name='resposta')),
            ],
            options={
                'verbose_name': 'Resposta de opção',
                'verbose_name_plural': 'Respostas de opção',
            },
            bases=('responses.answerbase',),
        ),
        migrations.CreateModel(
            name='AnswerSelect',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='responses.AnswerBase')),
                ('body', models.TextField(blank=True, null=True, verbose_name='resposta')),
            ],
            options={
                'verbose_name': 'Resposta de seleção',
                'verbose_name_plural': 'Respostas de seleção',
            },
            bases=('responses.answerbase',),
        ),
        migrations.CreateModel(
            name='AnswerSelectMultiple',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='responses.AnswerBase')),
                ('body', models.TextField(blank=True, null=True, verbose_name='resposta')),
            ],
            options={
                'verbose_name': 'Resposta de múltiplca escolha',
                'verbose_name_plural': 'Respostas de múltiplca escolha',
            },
            bases=('responses.answerbase',),
        ),
        migrations.CreateModel(
            name='AnswerText',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='responses.AnswerBase')),
                ('body', models.TextField(blank=True, null=True, verbose_name='resposta')),
            ],
            options={
                'verbose_name': 'Resposta aberta',
                'verbose_name_plural': 'Respostas abertas',
            },
            bases=('responses.answerbase',),
        ),
        migrations.CreateModel(
            name='OpenResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='responses.Response')),
            ],
            options={
                'verbose_name': 'Entrevista aberta',
                'verbose_name_plural': 'Entrevistas abertas',
            },
            bases=('responses.response',),
        ),
        migrations.CreateModel(
            name='RegionalResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='responses.Response')),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')], verbose_name='sexo')),
                ('age_group', models.PositiveIntegerField(choices=[(1, '16 a 24'), (2, '25 a 34'), (3, '35 a 44'), (4, '45 a 60'), (5, 'Acima de 60')], verbose_name='faixa etária')),
            ],
            options={
                'verbose_name': 'Entrevista regional',
                'verbose_name_plural': 'Entrevistas regionais',
            },
            bases=('responses.response',),
        ),
    ]
