# Generated by Django 3.0.2 on 2020-01-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        ('locations', '0001_initial'),
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerbase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.Question', verbose_name='pergunta'),
        ),
        migrations.AddField(
            model_name='answerbase',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='responses.Response', verbose_name='entrevista'),
        ),
        migrations.AddField(
            model_name='regionalresponse',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.City', verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='regionalresponse',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Neighborhood', verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='regionalresponse',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Sector', verbose_name='setor'),
        ),
        migrations.AddField(
            model_name='regionalresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.RegionalSurvey', verbose_name='pesquisa'),
        ),
        migrations.AddField(
            model_name='openresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.OpenSurvey', verbose_name='pesquisa'),
        ),
    ]
