# Generated by Django 3.0.2 on 2020-01-16 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_regionalsurvey_n_surveys'),
        ('responses', '0003_auto_20200110_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerbase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.Question', verbose_name='pergunta'),
        ),
    ]
