# Generated by Django 3.0.2 on 2020-01-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0004_auto_20200116_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='interview_uuid',
            field=models.CharField(default=1, max_length=36, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
