# Generated by Django 3.0.2 on 2020-01-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_regionalsurvey_n_surveys'),
        ('responses', '0005_response_interview_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='data de modificação')),
                ('body', models.TextField(blank=True, null=True, verbose_name='resposta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.Question', verbose_name='pergunta')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='responses.Response', verbose_name='entrevista')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.RemoveField(
            model_name='answernumeric',
            name='answerbase_ptr',
        ),
        migrations.RemoveField(
            model_name='answerradio',
            name='answerbase_ptr',
        ),
        migrations.RemoveField(
            model_name='answerselect',
            name='answerbase_ptr',
        ),
        migrations.RemoveField(
            model_name='answerselectmultiple',
            name='answerbase_ptr',
        ),
        migrations.RemoveField(
            model_name='answertext',
            name='answerbase_ptr',
        ),
        migrations.DeleteModel(
            name='AnswerBase',
        ),
        migrations.DeleteModel(
            name='AnswerNumeric',
        ),
        migrations.DeleteModel(
            name='AnswerRadio',
        ),
        migrations.DeleteModel(
            name='AnswerSelect',
        ),
        migrations.DeleteModel(
            name='AnswerSelectMultiple',
        ),
        migrations.DeleteModel(
            name='AnswerText',
        ),
    ]
