# Generated by Django 3.0.2 on 2020-01-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0006_auto_20200116_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['creation_date'], 'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
    ]
