# Generated by Django 3.0.2 on 2020-03-23 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20200313_2232'),
        ('responses', '0007_auto_20200116_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalresponse',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='locations.Neighborhood', verbose_name='bairro'),
        ),
    ]
