# Generated by Django 3.0.4 on 2020-06-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_auto_20200323_1546'),
        ('responses', '0008_auto_20200323_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalresponse',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='locations.City', verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='regionalresponse',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='locations.Sector', verbose_name='setor'),
        ),
    ]
