# Generated by Django 3.0.4 on 2020-08-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0009_auto_20200628_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalresponse',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')], verbose_name='gênero'),
        ),
    ]
