# Generated by Django 3.0.4 on 2020-09-04 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_auto_20200825_1501'),
        ('responses', '0010_auto_20200825_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalresponse',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='locations.Neighborhood', verbose_name='bairro'),
        ),
    ]
