# Generated by Django 3.1.2 on 2020-10-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0011_auto_20200904_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
    ]
