# Generated by Django 3.1.2 on 2024-07-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0013_response_control_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='interviewer',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Entrevistador'),
        ),
    ]
