# Generated by Django 3.0.2 on 2020-01-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200113_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrator'), (2, 'Entrevistador'), (3, 'Cliente')], null=True, verbose_name='tipo'),
        ),
    ]
