# Generated by Django 3.0.2 on 2020-01-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200114_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrator'), (2, 'Entrevistador'), (3, 'Contato do cliente')], null=True, verbose_name='tipo'),
        ),
    ]
