# Generated by Django 3.0.2 on 2020-01-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrador(a)'), (2, 'Entrevistador(a)'), (3, 'Contato do cliente')], null=True, verbose_name='tipo'),
        ),
    ]
