# Generated by Django 3.0.2 on 2020-01-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name', 'username'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
