# Generated by Django 3.0.2 on 2020-03-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200316_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('administrator', 'Administrador'), ('client', 'Cliente'), ('interviewer', 'Entrevistador')], default='administrator', max_length=100, verbose_name='tipo de usuário'),
        ),
    ]
