# Generated by Django 3.0.2 on 2020-01-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('n_male', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='porcentagem de homemes')),
                ('n_female', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='porcentagem de mulheres')),
                ('age_group_1', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='16 a 24 anos')),
                ('age_group_2', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='25 a 34 anos')),
                ('age_group_3', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='35 a 44 anos')),
                ('age_group_4', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='45 a 59 anos')),
                ('age_group_5', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='acima de 60 anos')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='locations.City', verbose_name='cidade')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('surveys_total', models.PositiveIntegerField(default=1, verbose_name='total de questionários')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='locations.Sector', verbose_name='setor')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'ordering': ['name'],
            },
        ),
    ]
