# Generated by Django 3.0.2 on 2020-01-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='surveys_total',
        ),
    ]
