# Generated by Django 3.0.2 on 2020-01-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_neighborhood_surveys_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='surveys_total',
            field=models.PositiveIntegerField(default=1, verbose_name='total de questionários'),
        ),
    ]
