# Generated by Django 3.0.2 on 2020-01-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_neighborhood_surveys_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='surveys_total',
            new_name='total_surveys',
        ),
    ]
