# Generated by Django 3.0.2 on 2020-01-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200116_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='total_surveys',
            new_name='surveys_total',
        ),
    ]
