# Generated by Django 3.0.2 on 2020-01-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20200116_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='surveys_total',
            new_name='max_responses',
        ),
    ]
