# Generated by Django 3.0.2 on 2020-01-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20200116_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['sector', 'name'], 'verbose_name': 'Bairro', 'verbose_name_plural': 'Bairros'},
        ),
    ]
