# Generated by Django 3.0.2 on 2020-01-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20200120_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['sector__city', 'sector', 'name'], 'verbose_name': 'Bairro', 'verbose_name_plural': 'Bairros'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['city', 'name'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
