# Generated by Django 3.0.2 on 2020-03-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20200120_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='n_responses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='número de questionários'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='max_responses',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='total de questionários'),
        ),
    ]
