# Generated by Django 3.0.4 on 2020-06-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_auto_20200323_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['pk'], 'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['sector__city', 'sector', 'pk', 'name'], 'verbose_name': 'Bairro', 'verbose_name_plural': 'Bairros'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['pk', 'city', 'name'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
