# Generated by Django 3.0.4 on 2020-08-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20200629_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-pk'], 'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['sector__city', 'sector', 'name', 'pk'], 'verbose_name': 'Bairro', 'verbose_name_plural': 'Bairros'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['city', 'name'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
