# Generated by Django 3.0.4 on 2020-08-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_auto_20200825_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
    ]
