# Generated by Django 3.1.2 on 2020-10-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_auto_20200825_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='age_group_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='16 a 24 anos'),
        ),
        migrations.AddField(
            model_name='sector',
            name='age_group_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='25 a 34 anos'),
        ),
        migrations.AddField(
            model_name='sector',
            name='age_group_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='35 a 44 anos'),
        ),
        migrations.AddField(
            model_name='sector',
            name='age_group_4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='45 a 59 anos'),
        ),
        migrations.AddField(
            model_name='sector',
            name='age_group_5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='acima de 60 anos'),
        ),
        migrations.AddField(
            model_name='sector',
            name='n_female',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='porcentagem de mulheres'),
        ),
        migrations.AddField(
            model_name='sector',
            name='n_male',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='porcentagem de homemes'),
        ),
    ]
