# Generated by Django 3.1.2 on 2020-10-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0016_auto_20201008_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['sector', 'name'], 'verbose_name': 'Bairro', 'verbose_name_plural': 'Bairros'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['city', 'pk'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
