# Generated by Django 3.0.2 on 2020-01-16 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20200116_1451'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0004_regionalsurvey_n_surveys'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInterviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='entrevistadora')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey', verbose_name='pesquisa')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalSurveyInterviewer',
            fields=[
                ('surveyinterviewer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.SurveyInterviewer')),
                ('sectors', models.ManyToManyField(blank=True, null=True, to='locations.Sector', verbose_name='setores')),
            ],
            bases=('surveys.surveyinterviewer',),
        ),
    ]
