# Generated by Django 3.0.2 on 2020-01-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20200117_1135'),
        ('surveys', '0006_auto_20200117_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalsurveyinterviewer',
            name='sectors',
            field=models.ManyToManyField(blank=True, null=True, related_name='surveyinterviewers', to='locations.Sector', verbose_name='setores'),
        ),
    ]
