# Generated by Django 3.0.2 on 2020-01-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20200117_1135'),
        ('surveys', '0007_auto_20200117_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalsurveyinterviewer',
            name='sectors',
            field=models.ManyToManyField(blank=True, null=True, to='locations.Sector', verbose_name='setores'),
        ),
        migrations.AlterField(
            model_name='surveyinterviewer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveyinterviewers', to='surveys.Survey', verbose_name='pesquisa'),
        ),
    ]
