# Generated by Django 3.0.2 on 2020-01-17 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0008_auto_20200117_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyinterviewer',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='entrevistadora'),
        ),
        migrations.AlterField(
            model_name='surveyinterviewer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewers', to='surveys.Survey', verbose_name='pesquisa'),
        ),
    ]
