# Generated by Django 3.0.2 on 2020-01-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20200117_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chart_type',
            field=models.CharField(choices=[('pie', 'pizza'), (' bar', 'barra')], default=' bar', max_length=25, verbose_name='tipo de gráfico'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('radio', 'radio'), ('select', 'select'), ('select-multiple', 'select multiple'), ('numeric', 'numeric')], default='text', max_length=25, verbose_name='tipo de questão'),
        ),
    ]
