# Generated by Django 3.0.2 on 2020-01-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_auto_20200121_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chart_type',
            field=models.CharField(choices=[('pie', 'pizza'), ('column', 'coluna')], default='column', max_length=25, verbose_name='tipo de gráfico'),
        ),
    ]
