# Generated by Django 3.0.2 on 2020-01-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_auto_20200121_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chart_type',
            field=models.CharField(choices=[('pie', 'pizza'), ('column', 'coluna'), ('comparator', 'comparador')], default='pie', max_length=25, verbose_name='tipo de gráfico'),
        ),
    ]
