# Generated by Django 3.0.2 on 2020-03-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_auto_20200316_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chart_type',
            field=models.CharField(choices=[('pie', 'pizza'), ('column', 'coluna'), ('comparator', 'comparador'), ('list', 'lista')], default='pie', max_length=25, verbose_name='tipo de gráfico'),
        ),
    ]
