# Generated by Django 3.0.2 on 2020-03-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20200313_2232'),
        ('surveys', '0014_auto_20200316_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionalsurvey',
            name='city',
        ),
        migrations.AddField(
            model_name='survey',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='locations.City', verbose_name='cidade'),
        ),
    ]
