# Generated by Django 3.0.2 on 2020-03-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_auto_20200323_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionalsurvey',
            old_name='max_responses',
            new_name='max_responses_s',
        ),
    ]
