# Generated by Django 3.0.4 on 2020-07-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_question_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.SlugField(blank=True, null=True, verbose_name='chave'),
        ),
    ]
