# Generated by Django 3.0.4 on 2020-07-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_auto_20200720_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='chave'),
        ),
    ]
