# Generated by Django 3.0.4 on 2020-08-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_opensurvey_max_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensurvey',
            name='open_form',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='formulário aberto ao público'),
        ),
    ]
