# Generated by Django 3.0.4 on 2020-08-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_auto_20200806_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensurvey',
            name='header',
            field=models.FileField(blank=True, null=True, upload_to='open', verbose_name='cabeçalho'),
        ),
    ]
