# Generated by Django 3.0.4 on 2020-08-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_opensurvey_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensurvey',
            name='bg_color',
            field=models.CharField(blank=True, default='#007BFF', max_length=50, null=True, verbose_name='cor do fundo'),
        ),
    ]
