# Generated by Django 3.0.4 on 2020-09-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0028_opensurvey_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalsurvey',
            name='no_neigh',
            field=models.BooleanField(default=False, verbose_name='pesquisa sem bairros'),
        ),
    ]
