# Generated by Django 3.0.4 on 2020-09-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0029_regionalsurvey_no_neigh'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='published',
            field=models.BooleanField(default=True, verbose_name='publicada'),
        ),
    ]
