# Generated by Django 3.1.2 on 2020-10-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0031_auto_20201006_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Pesquisa', 'verbose_name_plural': 'Pesquisas'},
        ),
    ]
