# Generated by Django 3.1.2 on 2020-10-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0032_auto_20201008_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Pesquisa', 'verbose_name_plural': 'Pesquisas'},
        ),
    ]
