# Generated by Django 3.1.2 on 2024-07-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0034_survey_enumerated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='enumerated',
            field=models.BooleanField(default=False, help_text='Para pesquisas feitas no papel enumerado o número de série de cara questionário deverá ser informado', verbose_name='enumerada'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='finalized',
            field=models.BooleanField(default=False, help_text='A pesquisa finalizada não estará mais disponível para as entrevistadoras', verbose_name='finalizado'),
        ),
    ]
