# Generated by Django 3.0.2 on 2020-01-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('segment', models.CharField(blank=True, max_length=100, null=True, verbose_name='segmento')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients', verbose_name='logo')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
