# Generated by Django 3.1.2 on 2020-10-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='segment',
        ),
    ]
